#!/usr/bin/env bash
# Build a minimal RPM-family rootfs (Fedora/AlmaLinux/RockyLinux) with
# dnf --installroot. A fresh installroot has no repo config of its own;
# how to borrow the bootstrap image's baked-in repos differs by dnf major:
#   dnf5 (Fedora 41+): loads NO host repos with --installroot unless
#     --use-host-config is passed (`-c` alone resolves zero repos).
#   dnf4 (EL9/EL10): doesn't know --use-host-config; `-c /etc/dnf/dnf.conf`
#     makes it read the host config and reposdir.
# Only default-enabled repos are used — wildcard-enabling everything pulls
# in debuginfo/source repos whose mirrorlists can be empty (Rocky 10).
# The distro's <release-package> is installed explicitly so the rootfs
# ends up with its own /etc/yum.repos.d (needed for the caller's later
# `chroot dnf upgrade` step, which has no host config to borrow from).
# ponytail: no historical snapshot pin (RPM distros lack a public
# timestamp-mirror service like snapshot.debian.org); the caller applies
# a build-time `dnf upgrade` for freshness instead. Add vault/point-release
# pinning for AlmaLinux/Rocky if true reproducibility is needed later.
# Usage: build-rootfs-rpm.sh <rootfs-dir> <releasever> <release-package>
set -euo pipefail

ROOTFS="${1:?rootfs dir required}"
RELEASEVER="${2:?releasever required}"
RELEASE_PKG="${3:?release package required (e.g. fedora-release, almalinux-release, rocky-release)}"

mkdir -p "${ROOTFS}"

# Rocky/Alma mirrorlists hand every build a random community mirror; a
# lagging one leaves freshly-released security updates uninstalled and the
# CVE gate then fails nondeterministically. Pin to the authoritative
# CDN-backed baseurl each repo file already ships commented out. Fedora is
# deliberately excluded: it uses metalink (checksum-verified, always
# current) and its commented baseurl is a dummy download.example host.
pin_authoritative_baseurl() {
  local f
  # EL8 ships capitalized file names (Rocky-BaseOS.repo); EL9+ lowercase.
  for f in "$1"/[Rr]ocky*.repo "$1"/almalinux*.repo; do
    [ -e "$f" ] || continue
    sed -i -e 's|^mirrorlist=|#mirrorlist=|' -e 's|^#[[:space:]]*baseurl=|baseurl=|' "$f"
  done
}

pin_authoritative_baseurl /etc/yum.repos.d

# EL8 base images don't ship findutils; hardening.sh (which runs later in
# the same bootstrap stage) needs `find`. Installs into the bootstrap
# image only — never into the rootfs being built.
command -v find >/dev/null 2>&1 || dnf install -y findutils

# dnf itself is included so 'full' keeps a working package manager (mirrors
# debootstrap minbase always including apt) and the caller's chroot upgrade
# step has a binary to run; hardening.sh strips it back out for 'micro'.
if command -v dnf5 >/dev/null 2>&1; then
  HOST_REPOS=(--use-host-config)
else
  HOST_REPOS=(-c /etc/dnf/dnf.conf)
fi

dnf install -y \
  --installroot="${ROOTFS}" \
  --releasever="${RELEASEVER}" \
  "${HOST_REPOS[@]}" \
  --setopt=install_weak_deps=False \
  --setopt=tsflags=nodocs \
  dnf coreutils-single glibc-minimal-langpack filesystem ca-certificates tzdata "${RELEASE_PKG}"

# Fedora keeps the rpmdb at /usr/lib/sysimage/rpm (F36+); ship the same
# compat symlink Fedora itself does so scanners and the structure tests
# find it at the traditional /var/lib/rpm path too. No-op on EL9/EL10.
if [ -d "${ROOTFS}/usr/lib/sysimage/rpm" ] && [ ! -e "${ROOTFS}/var/lib/rpm" ]; then
  ln -sfn ../../usr/lib/sysimage/rpm "${ROOTFS}/var/lib/rpm"
fi

# the rootfs's own repos (from the release package) drive the caller's
# later `chroot dnf upgrade`; pin those too so the upgrade can't resolve
# through a lagging mirror.
pin_authoritative_baseurl "${ROOTFS}/etc/yum.repos.d"

# ca-certificates ships its trust bundles as %ghost files generated by the
# %post scriptlet (update-ca-trust), which can fail silently under
# --installroot before the target's shell is laid down (Fedora), leaving
# /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem empty — the canonical
# bundle every other CA path symlinks to (Fedora 44 dropped the legacy
# /etc/pki/tls/certs/ca-bundle.crt symlink entirely). Regenerate inside
# the chroot when it's missing or empty. No-op on EL9/EL10.
if [ ! -s "${ROOTFS}/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem" ]; then
  chroot "${ROOTFS}" /usr/bin/update-ca-trust
fi

dnf clean all --installroot="${ROOTFS}"
rm -rf "${ROOTFS}/var/cache/dnf" \
       "${ROOTFS}/var/log/"* \
       "${ROOTFS}/tmp/"* 2>/dev/null || true

# --- Non-root user (matches distroless convention, same as deb family) ---
echo 'nonroot:x:65532:65532:nonroot:/home/nonroot:/sbin/nologin' >> "${ROOTFS}/etc/passwd"
echo 'nonroot:x:65532:' >> "${ROOTFS}/etc/group"
mkdir -p "${ROOTFS}/home/nonroot"
chown 65532:65532 "${ROOTFS}/home/nonroot"

# --- Reproducibility / privacy ---
: > "${ROOTFS}/etc/machine-id"
rm -f "${ROOTFS}/var/lib/dbus/machine-id"

echo "rootfs built: $(du -sh "${ROOTFS}" | cut -f1) (releasever: ${RELEASEVER})"
